# Student Performance Analysis using Pandas

## Objective

Analyze student performance data using Pandas to answer real-world analytical questions.

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('student_performance.csv')
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
749622,749623,17.6,72.7,4.8,90.8,A
749623,749624,12.7,84.8,6.4,73.0,B
749624,749625,15.6,97.2,6.1,100.0,A
749625,749626,22.7,75.8,5.3,100.0,A
749626,749627,13.8,NaN,NaN,NaN,NaN

### How many rows and columns are there in the dataset?

In [5]:
df.shape

(749627, 6)

### Show the first 10 rows of the dataset.

In [6]:
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [7]:
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
749617,749618,12.2,83.0,6.8,76.9,B
749618,749619,5.8,84.9,5.5,70.2,B
749619,749620,21.6,87.5,6.7,94.1,A
749620,749621,2.9,84.8,9.9,66.3,C
749621,749622,14.6,90.3,3.5,78.0,B
749622,749623,17.6,72.7,4.8,90.8,A
749623,749624,12.7,84.8,6.4,73.0,B
749624,749625,15.6,97.2,6.1,100.0,A
749625,749626,22.7,75.8,5.3,100.0,A
749626,749627,13.8,NaN,NaN,NaN,NaN

### What are the column names in the dataset?

In [8]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

### What is the maximum value of weekly_self_study_hours?

In [9]:
df['weekly_self_study_hours'].max()

40.0

### Which student studied the most hours in a week?

In [10]:
df.loc[df['weekly_self_study_hours'].max()]

student_id                    41
weekly_self_study_hours     20.2
attendance_percentage       85.6
class_participation          5.6
total_score                100.0
grade                          A
Name: 40, dtype: object

### Show the top 5 students by weekly_self_study_hours.

In [11]:
df.sort_values('weekly_self_study_hours',ascending=False).head(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
494825,494826,40.0,86.3,2.9,100.0,A
428200,428201,40.0,81.1,5.6,100.0,A
157322,157323,40.0,78.5,3.3,100.0,A
190334,190335,40.0,80.6,5.9,100.0,A
449084,449085,40.0,100.0,6.6,100.0,A

### Which student has the highest attendance percentage?

In [12]:
df[df['attendance_percentage'] == df['attendance_percentage'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
18,19,8.6,100.0,9.0,75.4,B
22,23,15.5,100.0,8.5,76.3,B
44,45,4.7,100.0,3.3,55.9,C
...,...,...,...,...,...,...
749517,749518,7.3,100.0,2.2,57.6,C
749530,749531,20.0,100.0,8.4,98.7,A
749552,749553,6.0,100.0,3.5,64.3,C
749584,749585,12.0,100.0,6.7,74.4,B
749592,749593,13.2,100.0,8.8,74.3,B

### Which student has the highest class participation?

In [13]:
df[df['class_participation']==df['class_participation'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
137,138,12.7,78.3,10.0,78.7,B
148,149,18.7,92.8,10.0,100.0,A
159,160,19.6,78.5,10.0,93.2,A
221,222,1.9,78.8,10.0,46.4,D
228,229,10.0,65.7,10.0,69.5,C
...,...,...,...,...,...,...
749488,749489,8.2,72.6,10.0,85.1,A
749490,749491,7.7,93.3,10.0,68.4,C
749506,749507,11.5,98.5,10.0,73.7,B
749519,749520,19.4,96.8,10.0,94.1,A
749573,749574,6.2,86.4,10.0,63.4,C

### Create a new column score_level
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

In [17]:
def score_level(x):
    if x >= 90:
        return 'High'
    elif 70 <= x < 90:
        return 'Medium'
    else:
        return 'Low'

In [19]:
df['score_level'] = df['total_score'].apply(score_level)
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
0,1,18.5,95.6,3.8,97.9,A,High
1,2,14.0,80.0,2.5,83.9,B,Medium
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
4,5,13.4,81.9,6.9,92.0,A,High
...,...,...,...,...,...,...,...
749622,749623,17.6,72.7,4.8,90.8,A,High
749623,749624,12.7,84.8,6.4,73.0,B,Medium
749624,749625,15.6,97.2,6.1,100.0,A,High
749625,749626,22.7,75.8,5.3,100.0,A,High
749626,749627,13.8,NaN,NaN,NaN,NaN,Low

### Which student has the highest total_score?

In [22]:
df[df['total_score']==df['total_score'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
6,7,26.1,81.8,5.9,100.0,A,High
17,18,17.2,74.0,8.1,100.0,A,High
20,21,25.3,89.3,6.4,100.0,A,High
...,...,...,...,...,...,...,...
749606,749607,21.6,88.3,6.3,100.0,A,High
749610,749611,24.8,79.6,4.3,100.0,A,High
749616,749617,12.8,78.5,1.5,100.0,A,High
749624,749625,15.6,97.2,6.1,100.0,A,High
749625,749626,22.7,75.8,5.3,100.0,A,High

### How many students scored exactly 100 in total_score?

In [24]:
df[df['total_score']==df['total_score'].max()].count()['student_id']

np.int64(201261)

In [25]:
len(df[df['total_score']==df['total_score'].max()])

201261

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

In [26]:
df['study_efficiency']= df['total_score']/df['weekly_self_study_hours']  # that's called broadcasting

In [27]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency
0,1,18.5,95.6,3.8,97.9,A,High,5.291892
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857
2,3,19.5,86.3,5.3,100.0,A,High,5.128205
3,4,25.7,70.2,7.0,100.0,A,High,3.891051
4,5,13.4,81.9,6.9,92.0,A,High,6.865672

### Create a new column study_category
"Light" if weekly_self_study_hours < 10,
"Moderate" if 10 ≤ hours ≤ 20,
"Heavy" if hours > 20

In [34]:
def category(x):
  if x<10:
    return 'Light'
  elif 10<= x <=20:
    return 'Moderate'
  else:
    return 'Heavy'

In [36]:
df['study_category'] = df['weekly_self_study_hours'].apply(category)

In [37]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency,study_category
0,1,18.5,95.6,3.8,97.9,A,High,5.291892,Moderate
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857,Moderate
2,3,19.5,86.3,5.3,100.0,A,High,5.128205,Moderate
3,4,25.7,70.2,7.0,100.0,A,High,3.891051,Heavy
4,5,13.4,81.9,6.9,92.0,A,High,6.865672,Moderate